added /tick (in new 1.20.3 file)
SpyglassMC/Spyglass pull request #1083
Opened 2023-10-26 22:22 UTC by InQuognito

2023-11-20 17:07 UTC, ChenCMD approved these changes
LGTM

2023-12-14 18:48 UTC, ChenCMD requested changes
We checked the operation again and found a problem.

2023-12-14 18:48 UTC, ChenCMD commented on src/data/CommandTree1.20.3.ts
> +                        [Switchable]: true,
Do not add Switchable when all children are not LiteralArgument.
```suggestion
```

2023-12-14 18:48 UTC, ChenCMD commented on src/data/CommandTree1.20.3.ts
> +                        [Switchable]: true,
Same as sprint.
and forgot to change.
```suggestion
                step: {
                    parser: new LiteralArgumentParser('step'),
                    children: {
```

2023-12-14 19:11 UTC, misode commented
Merging so Chen can continue this

2023-12-14 19:11 UTC, merged