WIP exclude improvements
SpyglassMC/Spyglass pull request #1607
Opened 2024-09-27 05:35 UTC by TheAfroOfDoom

2024-09-27 15:42 UTC, misode requested changes

2024-09-27 15:42 UTC, misode commented on packages/core/src/common/externals/index.ts
> +		options: WatchOptions,
This shouldn't directly use chokidar's `WatchOptions`, this is an interface that needs to be shared between the nodejs and browser externals

2024-09-27 15:42 UTC, misode commented on packages/core/src/service/Project.ts
> +			this.#excludePaths.push(...paths.map((path) => path.replace(/(\\|\/)$/, '')))
Since this is a chokidar specific requirement, this should be moved to the `NodeJsExternals` `watch` handler.

2024-09-27 15:42 UTC, misode commented on packages/core/src/service/Project.ts
> +	readonly #excludePaths: string[] = []
This is weirdly named, it should be `excludePatterns`

2024-09-27 15:42 UTC, misode commented on packages/core/src/service/Project.ts
> +						if (process.platform === 'win32') {
This will break in the browser

2024-09-27 16:35 UTC, TheAfroOfDoom commented
TODO should maybe also bump cache version

2024-12-30 18:23 UTC, misode commented
No longer relevant after #1695 was fixed. I did experiment briefly with passing the patterns to Chokidar, but passing a function made performance worse (because `shouldExclude` is not very cheap), and passing the raw patterns to be used by anymatch didn't work. Maybe this should be attempted again, but since the plan is to remove Chokidar (#1610), I don't think we should prioritize that.

2024-12-30 18:23 UTC, closed without merging